### ISSUE TITLE
Update documentation due to move from Woile/commitizen to commitizen-tools/commitizen

### ISSUE THREAD

**Issue by Lee-W** [commitizen-tools/commitizen#145]

**Comment by Lee-W** [comment]
The documentation has been updated. @Woile I might need your help to update the GitHub project URL, codecov, Travis and other external services. Thanks!

**Comment by Woile** [comment]
I'll check codecov, but we are not using travis

**Comment by Woile** [comment]
Fixed codecov

**Comment by Lee-W** [comment]
Thanks!

It seems that we still have some Travis settings. I'll remove it

But, we might need your help to update the link here.

![Screen Shot 2020-03-18 at 9 39 26 PM](https://user-images.githubusercontent.com/5144808/76966483-041d6180-6961-11ea-971c-00d029a0d2bb.png)

**Comment by Woile** [comment]
Yes, the travis settings can be removed, and the link has been updated

**Comment by Lee-W** [comment]
Nice! I just removed it. Close this issue 🎉
