### ISSUE TITLE
Not all versions in files get replaced

### ISSUE THREAD

**Issue by Peter-Slump** [commitizen-tools/commitizen#371]
## Description
Not all versions are replaced anymore.

In my project I create an Docker image based on the version tag and replace the version in a docker-compose file. However this version is not replaced since recent changes:

https://github.com/commitizen-tools/commitizen/commit/cd7018ebae89b76d9174d103407d140a1dd7bf09#diff-ed9bead31489109a8441fbfb00d2ddec00198489b0702bab164825c2d3bd9b4f

Regex is invalid for detecting versions.

## Steps to reproduce
1. Create a file e.g. docker-compose.py
2. Add version for an image: `image: my-container:v0.11.1`
3. Bump version using commitizen

## Current behavior
Version is not updated in file

## Desired behavior
Version is also updated in file

## Environment
https://github.com/commitizen-tools/commitizen/commit/cd7018ebae89b76d9174d103407d140a1dd7bf09#diff-ed9bead31489109a8441fbfb00d2ddec00198489b0702bab164825c2d3bd9b4f

bump.py:192

- commitizen version: 2.17.0
- python version: 3.8.7
- operating system: Linux

**Comment by Lee-W** [comment]
Hi, we're recently working on it. You could follow the discussion on https://github.com/commitizen-tools/commitizen/pull/370. or try 2.16.0.

**Comment by Woile** [comment]
Please check again using `v2.17.2`, it should fix it 🎉

**Comment by Peter-Slump** [comment]
Sorry the issues is not resolved in v2.17.2. I've create a PR to show the issue and also applied a fix for it. Please check.

**Comment by Woile** [comment]
Thanks @Peter-Slump !! We have also released version `2.17.3` which in theory should finally fix this, could you check first with that version, if it solves your issue.

Thanks 👍🏻

**Comment by Peter-Slump** [comment]
Hi @Woile I just ran the CI/CD pipeline based on 2.17.3 however it was not fixed there. Please view my PR to find out what the exact issue is.
